/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Modele;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Date;

import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.BorderLayout;
import java.io.File;
import java.io.FileOutputStream;
import java.text.DateFormat;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author oussema
 */
public class Contrat extends javax.swing.JFrame {
    private JPanel contentPane;

    Connection con;
    PreparedStatement pst;
    ResultSet rs;

    /**
     * Creates new form Test
     */
    public Contrat() {
        initComponents();
        Tablelouer();
        vo();
        cl();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void Connect(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/voiture","root","");
            System.out.println("Connecter");
            
        
        } catch (ClassNotFoundException | SQLException e){
            //si il ya une erreur

        }
    } 
    private boolean verify(String matricule, String dd, String df, String nb, String pj, String pt) {
    // Vérification du matricule
    boolean is_valid = true;
    matValid.setText("");
    ddValid.setText("");
    dfValid.setText("");
    nbValid.setText("");
    pjValid.setText("");
    ptValid.setText("");
    
    if(nb==null || nb.isEmpty()){
            nbValid.setText("cliquer sur set jour");
            is_valid=false;
    }
    if(pj==null || pj.isEmpty()){
            pjValid.setText("cliquer sur set voiture");
            is_valid=false;
    }
    if(pt==null || pt.isEmpty()){
            nbValid.setText("cliquer sur set prix");
            is_valid=false;
    }
    if (matricule == null || !matricule.matches("[A-Za-z0-9-]+")) {
        matValid.setText("matricule invalide");
        is_valid=false;
    }
    
    LocalDate locDate;
    try {
        locDate = LocalDate.parse(dd, DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        if (locDate.isBefore(LocalDate.now())) {
            ddValid.setText("la date doit etre au futur");
            is_valid= false;
        }
    } catch (DateTimeParseException e) {
        ddValid.setText("date format dd/MM/yyyy");
        is_valid= false;
    }
    LocalDate locDate2;
    try {
        locDate2 = LocalDate.parse(df, DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        locDate = LocalDate.parse(dd, DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        if (locDate2.isBefore(locDate)) {
            dfValid.setText("la date doit etre > date debut");
            is_valid= false;
        }
    } catch (DateTimeParseException e) {
        dfValid.setText("date format dd/MM/yyyy");
        is_valid= false;
    }
    
    return is_valid;
}
    private void Tablelouer(){
       String[] voiture = {"matricule","id client","matricule voiture","date de départ","date finale","prix","etat"};
       String [] vue = new String[8];
        
       DefaultTableModel model = new DefaultTableModel(null,voiture);
        
       String sql = "select * from louer";
       try{
           Connect();
           Statement st = con.createStatement();
           rs = st.executeQuery(sql);
           while (rs.next()){
               vue[0] = rs.getString("matriculeL");
               vue[1] = rs.getString("id");
               vue[2] = rs.getString("matricule");
               vue[3] = rs.getString("date_debut");
               vue[4] = rs.getString("date_fin");
               vue[5] = rs.getString("prix");
               vue[6] = rs.getString("etat");
               model.addRow(vue);
           }
           //affichage dans la table
           Table1.setModel(model);
           //toujours fermer la base de donnee
           con.close();
            
            
        } catch (SQLException e){
        }
    }
    private void Prixvo(){
        try{
            Connect();
            String sql = "select prix from voiture_enregistrer where matricule=?";
            pst = con.prepareStatement(sql);
            pst.setString(1, txtmatricule.getSelectedItem().toString());
            rs = pst.executeQuery();
            while (rs.next()){
                txtprixvoiture.setText(rs.getString("prix"));
            }
            con.close();
        } catch (Exception e){
            e.printStackTrace();
        }
    }
    private void vo(){
        try{
            Connect();
            String sql = "select matricule from voiture_enregistrer";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()){
                txtmatricule.addItem(rs.getString("matricule"));
            }
            con.close();
        } catch (Exception e){
            e.printStackTrace();
        }
    }
    private void cl(){
        try{
            Connect();
            String sql = "select id from client";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()){
                txtid.addItem(rs.getString("id"));
            }
            con.close();
        } catch (Exception e){
            e.printStackTrace();
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtid = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dtfin = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        txtprixvoiture = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nbj = new javax.swing.JTextField();
        txtprix = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtmatricule = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        dtdebut = new javax.swing.JFormattedTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        txtmatriculec = new javax.swing.JTextField();
        matValid = new javax.swing.JLabel();
        ddValid = new javax.swing.JLabel();
        dfValid = new javax.swing.JLabel();
        ptValid = new javax.swing.JLabel();
        nbValid = new javax.swing.JLabel();
        pjValid = new javax.swing.JLabel();
        pdf = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Contrat");
        jLabel1.setToolTipText("");
        jLabel1.setAutoscrolls(true);
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setInheritsPopupMenu(false);
        jLabel1.setRequestFocusEnabled(false);

        txtid.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("ID de Client");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Matricule de Contrat");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Prix par jour");

        dtfin.setBackground(new java.awt.Color(204, 0, 0));
        try {
            dtfin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dtfin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dtfin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtfinActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Date fin");

        txtprixvoiture.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtprixvoiture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprixvoitureActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Prix totale");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Nombre de Jour");

        nbj.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nbj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbjActionPerformed(evt);
            }
        });

        txtprix.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtprix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprixActionPerformed(evt);
            }
        });

        Table1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table1);

        jButton1.setText("Modifier");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Annuler");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Actualiser");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Fermer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Enregistrer");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Date debut");

        txtmatricule.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtmatricule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmatriculeActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Matricule de Voiture");

        dtdebut.setBackground(new java.awt.Color(0, 153, 0));
        try {
            dtdebut.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dtdebut.setToolTipText("");
        dtdebut.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        dtdebut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dtdebut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtdebutActionPerformed(evt);
            }
        });

        jButton6.setText("Set Voiture");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Set Prix");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Set Jour");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Sélectionner Contrat");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        txtmatriculec.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtmatriculec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmatriculecActionPerformed(evt);
            }
        });

        matValid.setForeground(new java.awt.Color(255, 0, 0));

        ddValid.setForeground(new java.awt.Color(255, 0, 0));

        dfValid.setForeground(new java.awt.Color(255, 0, 0));

        ptValid.setForeground(new java.awt.Color(255, 0, 0));

        nbValid.setForeground(new java.awt.Color(255, 0, 0));

        pjValid.setForeground(new java.awt.Color(255, 0, 0));

        pdf.setForeground(new java.awt.Color(255, 51, 51));
        pdf.setText("Genérer Pdf");
        pdf.setActionCommand("genererPdf");
        pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genererPdf(evt);
            }
        });

        jButton10.setText("Supprimer");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(txtprix, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(matValid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtmatriculec, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(dtdebut, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(txtid, javax.swing.GroupLayout.Alignment.TRAILING, 0, 210, Short.MAX_VALUE)
                                                .addComponent(dtfin, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(nbj, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(txtprixvoiture, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(ddValid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(dfValid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(nbValid)
                                                .addComponent(pjValid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(txtmatricule, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(44, 44, 44)
                                                .addComponent(pdf)))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ptValid, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(235, 235, 235)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtmatriculec, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(matValid)
                                .addGap(4, 4, 4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtmatricule, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 68, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dtdebut, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(2, 2, 2)
                                .addComponent(ddValid))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pdf)
                                .addGap(38, 38, 38)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dtfin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1)
                                .addComponent(dfValid)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nbj, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nbValid)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtprixvoiture, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)))
                        .addComponent(pjValid)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtprix, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ptValid)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(41, 41, 41))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1365, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // Récupération des dates dans les zones de texte
        String debutStr = dtdebut.getText();
        String finStr = dtfin.getText();

        // Conversion des dates en objets Date
        Date debut = null;
        Date fin = null;
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            debut = sdf.parse(debutStr);
            fin = sdf.parse(finStr);
        } catch (Exception ex) {
            nbj.setText("Format de date invalide");
            return;
        }

        // Calcul du nombre de jours
        long diffMillis = fin.getTime() - debut.getTime();
        int nbJours = (int) (diffMillis / (1000 * 60 * 60 * 24) + 1);

        // Affichage du nombre de jours dans la zone de texte nbj
        nbj.setText(Integer.toString(nbJours));

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // Récupération de nombre de jours et prix par jour
        String nbjstr = nbj.getText();
        String prixvoiture = txtprixvoiture.getText();

        //convertir les données de string en integer
        int nb = Integer.parseInt(nbjstr);
        int pr = Integer.parseInt(prixvoiture);
        //Calcule de prix totale
        int s = nb*pr;
        txtprix.setText(Integer.toString(s));
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Prixvo();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtmatriculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmatriculeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmatriculeActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String etat = "En cours";
        try{
            boolean valid= verify(txtmatriculec.getText(),dtdebut.getText(),dtfin.getText(),nbj.getText(),txtprixvoiture.getText(),txtprix.getText());
            if(valid){
            Connect();
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            java.util.Date parsedDate = dateFormat.parse(dtdebut.getText());
            java.sql.Date sqlDated = new java.sql.Date(parsedDate.getTime());

             SimpleDateFormat dateFormat2 = new SimpleDateFormat("dd/MM/yyyy");
            java.util.Date parsedDate2 = dateFormat2.parse(dtfin.getText());
            java.sql.Date sqlDatef = new java.sql.Date(parsedDate.getTime());
            
            pst = con.prepareStatement("insert into louer(matriculeL,id,matricule,date_debut,date_fin,prix,etat)"+"values(?,?,?,?,?,?,?)");
            pst.setString(1, txtmatriculec.getText());
            pst.setString(2, txtid.getSelectedItem().toString());
            pst.setString(3, txtmatricule.getSelectedItem().toString());
            pst.setDate(4, sqlDated);
            pst.setDate(5, sqlDatef);
            pst.setString(6, txtprix.getText());
            pst.setString(7, etat);
            pst.executeUpdate();
            con.close();
            JOptionPane.showMessageDialog(null, "voiture "+txtmatricule.getSelectedItem().toString()+" louer");
            Tablelouer();}

        } catch (Exception e){
             JOptionPane.showMessageDialog(null, "voiture dejà louer");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Contrat.super.dispose();
        MenuPrincipale men = new MenuPrincipale();
        men.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        txtprixvoiture.setText("");
        txtprix.setText("");
        dtdebut.setText("");
        dtfin.setText("");
        nbj.setText("");
        txtprixvoiture.setText("");
        matValid.setText("");
        ddValid.setText("");
        dfValid.setText("");
        nbValid.setText("");
        pjValid.setText("");
        ptValid.setText("");

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String etat = "En cours";                                         
    try {
        boolean valid = verify(txtmatriculec.getText(), dtdebut.getText(), dtfin.getText(), nbj.getText(), txtprixvoiture.getText(), txtprix.getText());
        if (valid) {
            Connect();
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            java.util.Date parsedDate = dateFormat.parse(dtdebut.getText());
            java.sql.Date sqlDated = new java.sql.Date(parsedDate.getTime());

            SimpleDateFormat dateFormat2 = new SimpleDateFormat("dd/MM/yyyy");
            java.util.Date parsedDate2 = dateFormat2.parse(dtfin.getText());
            java.sql.Date sqlDatef = new java.sql.Date(parsedDate2.getTime());

            pst = con.prepareStatement("UPDATE louer SET id = ?, matricule = ?, date_debut = ?, date_fin = ?, prix = ?, etat = ? WHERE matriculeL = ?");
            pst.setString(7, txtmatriculec.getText());
            pst.setString(1, txtid.getSelectedItem().toString());
            pst.setString(2, txtmatricule.getSelectedItem().toString());
            pst.setDate(3, sqlDated);
            pst.setDate(4, sqlDatef);
            pst.setString(5, txtprix.getText());
            pst.setString(6, etat);

            int rowsUpdated = pst.executeUpdate();
            con.close();
            if (rowsUpdated > 0) {
                JOptionPane.showMessageDialog(null, "Location mise à jour pour l'ID " + txtid.getSelectedItem().toString());
                Tablelouer();
            } else {
                JOptionPane.showMessageDialog(null, "Aucune location trouvée avec l'ID " + txtid.getSelectedItem().toString());
            }
        }
    } catch (Exception e) {
        e.printStackTrace();
    }



            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Table1MouseClicked

    private void nbjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nbjActionPerformed

    private void genererPdf(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genererPdf
        try {
            // Create a new iText Document object
            Document document = new Document(PageSize.A4, 50, 50, 50, 50);
            PdfWriter.getInstance(document, new FileOutputStream("contrat.pdf"));
            document.open();
            
            // Add a Paragraph to the document with the current date and time
            DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
            Date date = new Date();
            Paragraph dateTime = new Paragraph("Generated on " + dateFormat.format(date),
                    FontFactory.getFont(FontFactory.HELVETICA, 14, Font.NORMAL));
            dateTime.setAlignment(Element.ALIGN_CENTER);
            document.add(dateTime);
            document.add(new Paragraph("\n\n"));
            
            // Add the Swing screen contents to the document
            // Example: Add a table with some data
            
            document.add(new Paragraph("----------------------------------------"));
            document.add(new Paragraph("----------------------------------------"));
            document.add(new Paragraph("Matricule de Contrat :"+ txtmatriculec.getText()));
            document.add(new Paragraph("Matricule de voiture :"+txtmatricule.getSelectedItem()));
            document.add(new Paragraph("ID client :"+txtid.getSelectedItem()));
            document.add(new Paragraph("Date debut :"+dtdebut.getText()));
            document.add(new Paragraph("Date fin :"+dtfin.getText()));
            int nbj1=Integer.parseInt(nbj.getText());
            document.add(new Paragraph("Nombre de jour :"+nbj1));
            int pr=Integer.parseInt(txtprixvoiture.getText());
            document.add(new Paragraph("Prix de jour :"+pr));
            document.add(new Paragraph("Prix totale :"+txtprix.getText()));
            document.add(new Paragraph("----------------------------------------"));
            document.add(new Paragraph("----------------------------------------"));

            // Save and close the document
            document.close();
            JOptionPane.showMessageDialog(null, "PDF generated successfully!");
             
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error generating PDF: " + ex.getMessage());
        }
    }//GEN-LAST:event_genererPdf

    private void txtmatriculecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmatriculecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmatriculecActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void dtdebutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtdebutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dtdebutActionPerformed

    private void dtfinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtfinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dtfinActionPerformed

    private void txtprixvoitureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprixvoitureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprixvoitureActionPerformed

    private void txtprixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprixActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        int selectionner = Table1.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)Table1.getModel();
        txtmatriculec.setText(model.getValueAt(selectionner, 0).toString());
        txtid.setSelectedItem(model.getValueAt(selectionner, 1).toString());
        //txtid.setText(model.getValueAt(selectionner, 1).toString());
        txtmatricule.setSelectedItem(model.getValueAt(selectionner, 2).toString());

        String inputDate = model.getValueAt(selectionner, 3).toString();
        LocalDate date = LocalDate.parse(inputDate);
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        String outputDate = date.format(formatter);
        dtdebut.setText(outputDate);
        String inputDatef = model.getValueAt(selectionner, 4).toString();
        LocalDate datef = LocalDate.parse(inputDatef);
        DateTimeFormatter formatterf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        String outputDatef = date.format(formatterf);
        dtfin.setText(outputDatef);
        //dtfin.setText(model.getValueAt(selectionner, 4).toString());
        txtprix.setText(model.getValueAt(selectionner, 5).toString());

    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String etat = "Arrive"; 
        try {
            Connect();

            pst = con.prepareStatement("UPDATE louer SET etat = ? WHERE matriculeL = ?");
            pst.setString(2, txtmatriculec.getText());
            pst.setString(1, etat);

            int rowsUpdated = pst.executeUpdate();
            con.close();
            if (rowsUpdated > 0) {
                JOptionPane.showMessageDialog(null, "Location mise à jour pour l'ID " + txtid.getSelectedItem().toString());
                Tablelouer();
            } else {
                JOptionPane.showMessageDialog(null, "Aucune location trouvée avec l'ID " + txtid.getSelectedItem().toString());
            }
        }
     catch (Exception e) {
        e.printStackTrace();
     }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        try{
            Connect();
            pst = con.prepareStatement("delete from louer where matriculeL=?");
            int id = Table1.getSelectedRow();
            String select = (String)Table1.getValueAt(id, 0);
            pst.setString(1, select);
            pst.executeUpdate();
            con.close();
            JOptionPane.showMessageDialog(null, txtmatriculec.getText()+"supprimer");
            Tablelouer();
        } catch (Exception e){
            e.printStackTrace();
            JOptionPane.showConfirmDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contrat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contrat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contrat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contrat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contrat().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table1;
    private javax.swing.JLabel ddValid;
    private javax.swing.JLabel dfValid;
    private javax.swing.JFormattedTextField dtdebut;
    private javax.swing.JFormattedTextField dtfin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel matValid;
    private javax.swing.JLabel nbValid;
    private javax.swing.JTextField nbj;
    private javax.swing.JButton pdf;
    private javax.swing.JLabel pjValid;
    private javax.swing.JLabel ptValid;
    private javax.swing.JComboBox<String> txtid;
    private javax.swing.JComboBox<String> txtmatricule;
    private javax.swing.JTextField txtmatriculec;
    private javax.swing.JTextField txtprix;
    private javax.swing.JTextField txtprixvoiture;
    // End of variables declaration//GEN-END:variables
}
